
version: '3.8'

services:
  # Orchestration Layer
  orchestration:
    build: ./services/orchestration
    ports:
      - "8000:8000"
    environment:
      - LLM_INFERENCE_URL=http://llm-inference:8001
      - LLAMAINDEX_URL=http://llamaindex-service:8002
      - N8N_URL=http://n8n:5678
      - MONITORING_URL=http://grafana:3000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - llm-inference
      - llamaindex-service

  # LLM Inference Service
  llm-inference:
    build: ./services/llm-inference
    ports:
      - "8001:8001"
    environment:
      - LLAMA3_ENDPOINT=http://llama3-service:8000
      - MISTRAL_ENDPOINT=http://mistral-service:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # LlamaIndex RAG Service
  llamaindex-service:
    build: ./services/llamaindex-service
    ports:
      - "8002:8002"
    volumes:
      - ./data/vector_stores:/app/vector_stores
      - ./data/documents:/app/documents

  # n8n Workflows
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres

  # Monitoring Stack
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  # Supporting Services
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  n8n_data:
  grafana_data:
  prometheus_data:
  redis_data:
  postgres_data:
