
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-inference
  namespace: ai-models
  labels:
    app: llm-inference
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-inference
  template:
    metadata:
      labels:
        app: llm-inference
    spec:
      containers:
      - name: llm-inference
        image: llm-inference:latest
        ports:
        - containerPort: 8001
        env:
        - name: LLAMA3_ENDPOINT
          value: "http://llama3-70b-service:8000"
        - name: MISTRAL_ENDPOINT
          value: "http://mistral-service:8000"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: model-secrets
              key: gemini-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: llm-inference-service
  namespace: ai-models
spec:
  selector:
    app: llm-inference
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP
