// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vydevqjpfwlizelblavb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5ZGV2cWpwZndsaXplbGJsYXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzM0MzIsImV4cCI6MjA2MzQwOTQzMn0.3FADPwJRgPivj3AlKqTyz6xCDqq8emAG1wykKjr2ZK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);